version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        auth:
          username: vadimGV
          password: OOuumfo6RbQ
    steps:
      - checkout
      - run:
          command: |
            mkdir test-results
            sudo pip install -r requirements.txt
      - run:
          command: |
            pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1